sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in test-k8s.json.enc -out test-k8s.json -d
# Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
# install kubectl command
  - gcloud components update kubectl
# Need to create service account on GC to use for the next command
  - gcloud auth activate-service-account --key-file service-account.json
