apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: paulinoj-com-tls
spec:
  secretName: paulinoj-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: paulinoj.com
  dnsNames:
    - paulinoj.com
    - www.paulinoj.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - paulinoj.com
          - www.paulinoj.com