apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: paulinoj/multi-server
          ports:
            - containerPort: 5000
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              #environmental variables must be provided as strings, not integers
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  # indicate name of secret
                  # need to indicate key because can store several key/value pairs
                  # inside of secret
                  name: pgpassword
                  key: PGPASSWORD


# secret password is created imperatively in production environment
# kubectl create secret generic pgpassword --from-literal PGPASSWORD=whatever

  